/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FSAE_FSAE_TELEMETRY_PB_H_INCLUDED
#define PB_FSAE_FSAE_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _fsae_AlarmSeverity {
    fsae_AlarmSeverity_ALARM_SEVERITY_UNSPECIFIED = 0,
    fsae_AlarmSeverity_ALARM_SEVERITY_INFO = 1,
    fsae_AlarmSeverity_ALARM_SEVERITY_WARNING = 2,
    fsae_AlarmSeverity_ALARM_SEVERITY_ERROR = 3,
    fsae_AlarmSeverity_ALARM_SEVERITY_FATAL = 4
} fsae_AlarmSeverity;

typedef enum _fsae_DrivingMode {
    fsae_DrivingMode_DRIVING_MODE_UNSPECIFIED = 0,
    fsae_DrivingMode_DRIVING_MODE_STANDBY = 1,
    fsae_DrivingMode_DRIVING_MODE_READY = 2,
    fsae_DrivingMode_DRIVING_MODE_DRIVE = 3,
    fsae_DrivingMode_DRIVING_MODE_FAULT = 4
} fsae_DrivingMode;

typedef enum _fsae_ImdState {
    fsae_ImdState_IMD_STATE_UNSPECIFIED = 0,
    fsae_ImdState_IMD_STATE_NORMAL = 1,
    fsae_ImdState_IMD_STATE_WARNING = 2,
    fsae_ImdState_IMD_STATE_FAULT = 3
} fsae_ImdState;

typedef enum _fsae_WorkState {
    fsae_WorkState_WORK_STATE_UNSPECIFIED = 0,
    fsae_WorkState_WORK_STATE_OFF = 1,
    fsae_WorkState_WORK_STATE_PRECHARGE = 2,
    fsae_WorkState_WORK_STATE_ON = 3,
    fsae_WorkState_WORK_STATE_FAULT = 4
} fsae_WorkState;

typedef enum _fsae_VcuStatus {
    fsae_VcuStatus_VCU_STATUS_UNSPECIFIED = 0,
    fsae_VcuStatus_VCU_STATUS_OFF = 1,
    fsae_VcuStatus_VCU_STATUS_PRECHARGE = 2,
    fsae_VcuStatus_VCU_STATUS_HV_ENABLED = 3,
    fsae_VcuStatus_VCU_STATUS_FAULT = 4
} fsae_VcuStatus;

typedef enum _fsae_MotorPosition {
    fsae_MotorPosition_MOTOR_POSITION_UNSPECIFIED = 0,
    fsae_MotorPosition_MOTOR_POSITION_FRONT_LEFT = 1,
    fsae_MotorPosition_MOTOR_POSITION_FRONT_RIGHT = 2,
    fsae_MotorPosition_MOTOR_POSITION_REAR_LEFT = 3,
    fsae_MotorPosition_MOTOR_POSITION_REAR_RIGHT = 4
} fsae_MotorPosition;

/* Struct definitions */
typedef struct _fsae_PacketHeader {
    uint32_t timestamp_ms;
    uint32_t seq;
    uint32_t source_id;
} fsae_PacketHeader;

typedef struct _fsae_Alarm {
    uint32_t alarm_id;
    fsae_AlarmSeverity severity;
    char message[64];
} fsae_Alarm;

typedef struct _fsae_FastTelemetry {
    int32_t hv_voltage_dv;
    int32_t hv_current_ma;
    int32_t battery_temp_max_c;
    fsae_DrivingMode driving_mode;
    uint32_t speed_kmh;
} fsae_FastTelemetry;

typedef struct _fsae_BmsSummary {
    uint32_t total_voltage;
    int32_t total_current;
    uint32_t soc_pct;
    int32_t max_temp_c;
    int32_t min_temp_c;
    uint32_t max_cell_mv;
    uint32_t min_cell_mv;
    fsae_ImdState imd_state;
    fsae_WorkState work_state;
} fsae_BmsSummary;

typedef struct _fsae_BatteryModule {
    uint32_t module_id;
    pb_size_t cell_mv_count;
    uint32_t cell_mv[23];
    pb_size_t temp_dc_count;
    int32_t temp_dc[8];
} fsae_BatteryModule;

typedef struct _fsae_BmsDetail {
    pb_size_t modules_count;
    fsae_BatteryModule modules[6];
} fsae_BmsDetail;

typedef struct _fsae_ThermalRawChunk {
    fsae_MotorPosition position;
    uint32_t frame_id;
    uint32_t chunk_index;
    uint32_t chunk_count;
    int32_t pixel_temp_dc;
} fsae_ThermalRawChunk;

typedef struct _fsae_ThermalSensorSummary {
    fsae_MotorPosition position;
    int32_t min_temp_dc;
    int32_t max_temp_dc;
    int32_t avg_temp_dc;
    pb_size_t chunks_count;
    fsae_ThermalRawChunk chunks[4];
} fsae_ThermalSensorSummary;

typedef struct _fsae_ThermalSummary {
    pb_size_t sensors_count;
    fsae_ThermalSensorSummary sensors[4];
} fsae_ThermalSummary;

typedef struct _fsae_MotorState {
    fsae_MotorPosition position;
    int32_t rpm;
    int32_t torque_nm;
    int32_t power_w;
    int32_t motor_temp_dc;
    int32_t inverter_temp_dc;
    int32_t motor_error;
} fsae_MotorState;

typedef struct _fsae_VehicleState {
    uint32_t speed_kmh;
    fsae_DrivingMode driving_mode;
    uint32_t throttle_position;
    uint32_t brake_position;
    bool ready_to_drive;
    fsae_VcuStatus vcu_status;
    pb_size_t motors_count;
    fsae_MotorState motors[4];
} fsae_VehicleState;

typedef struct _fsae_TelemetryFrame {
    bool has_packet_header;
    fsae_PacketHeader packet_header;
    bool has_fast_telemetry;
    fsae_FastTelemetry fast_telemetry;
    bool has_vehicle_state;
    fsae_VehicleState vehicle_state;
    bool has_bms_summary;
    fsae_BmsSummary bms_summary;
    bool has_bms_detail;
    fsae_BmsDetail bms_detail;
    bool has_thermal_summary;
    fsae_ThermalSummary thermal_summary;
    pb_callback_t alarm;
} fsae_TelemetryFrame;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _fsae_AlarmSeverity_MIN fsae_AlarmSeverity_ALARM_SEVERITY_UNSPECIFIED
#define _fsae_AlarmSeverity_MAX fsae_AlarmSeverity_ALARM_SEVERITY_FATAL
#define _fsae_AlarmSeverity_ARRAYSIZE ((fsae_AlarmSeverity)(fsae_AlarmSeverity_ALARM_SEVERITY_FATAL+1))

#define _fsae_DrivingMode_MIN fsae_DrivingMode_DRIVING_MODE_UNSPECIFIED
#define _fsae_DrivingMode_MAX fsae_DrivingMode_DRIVING_MODE_FAULT
#define _fsae_DrivingMode_ARRAYSIZE ((fsae_DrivingMode)(fsae_DrivingMode_DRIVING_MODE_FAULT+1))

#define _fsae_ImdState_MIN fsae_ImdState_IMD_STATE_UNSPECIFIED
#define _fsae_ImdState_MAX fsae_ImdState_IMD_STATE_FAULT
#define _fsae_ImdState_ARRAYSIZE ((fsae_ImdState)(fsae_ImdState_IMD_STATE_FAULT+1))

#define _fsae_WorkState_MIN fsae_WorkState_WORK_STATE_UNSPECIFIED
#define _fsae_WorkState_MAX fsae_WorkState_WORK_STATE_FAULT
#define _fsae_WorkState_ARRAYSIZE ((fsae_WorkState)(fsae_WorkState_WORK_STATE_FAULT+1))

#define _fsae_VcuStatus_MIN fsae_VcuStatus_VCU_STATUS_UNSPECIFIED
#define _fsae_VcuStatus_MAX fsae_VcuStatus_VCU_STATUS_FAULT
#define _fsae_VcuStatus_ARRAYSIZE ((fsae_VcuStatus)(fsae_VcuStatus_VCU_STATUS_FAULT+1))

#define _fsae_MotorPosition_MIN fsae_MotorPosition_MOTOR_POSITION_UNSPECIFIED
#define _fsae_MotorPosition_MAX fsae_MotorPosition_MOTOR_POSITION_REAR_RIGHT
#define _fsae_MotorPosition_ARRAYSIZE ((fsae_MotorPosition)(fsae_MotorPosition_MOTOR_POSITION_REAR_RIGHT+1))


#define fsae_Alarm_severity_ENUMTYPE fsae_AlarmSeverity

#define fsae_FastTelemetry_driving_mode_ENUMTYPE fsae_DrivingMode

#define fsae_BmsSummary_imd_state_ENUMTYPE fsae_ImdState
#define fsae_BmsSummary_work_state_ENUMTYPE fsae_WorkState



#define fsae_ThermalRawChunk_position_ENUMTYPE fsae_MotorPosition

#define fsae_ThermalSensorSummary_position_ENUMTYPE fsae_MotorPosition


#define fsae_MotorState_position_ENUMTYPE fsae_MotorPosition

#define fsae_VehicleState_driving_mode_ENUMTYPE fsae_DrivingMode
#define fsae_VehicleState_vcu_status_ENUMTYPE fsae_VcuStatus



/* Initializer values for message structs */
#define fsae_PacketHeader_init_default           {0, 0, 0}
#define fsae_Alarm_init_default                  {0, _fsae_AlarmSeverity_MIN, ""}
#define fsae_FastTelemetry_init_default          {0, 0, 0, _fsae_DrivingMode_MIN, 0}
#define fsae_BmsSummary_init_default             {0, 0, 0, 0, 0, 0, 0, _fsae_ImdState_MIN, _fsae_WorkState_MIN}
#define fsae_BatteryModule_init_default          {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define fsae_BmsDetail_init_default              {0, {fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default}}
#define fsae_ThermalRawChunk_init_default        {_fsae_MotorPosition_MIN, 0, 0, 0, 0}
#define fsae_ThermalSensorSummary_init_default   {_fsae_MotorPosition_MIN, 0, 0, 0, 0, {fsae_ThermalRawChunk_init_default, fsae_ThermalRawChunk_init_default, fsae_ThermalRawChunk_init_default, fsae_ThermalRawChunk_init_default}}
#define fsae_ThermalSummary_init_default         {0, {fsae_ThermalSensorSummary_init_default, fsae_ThermalSensorSummary_init_default, fsae_ThermalSensorSummary_init_default, fsae_ThermalSensorSummary_init_default}}
#define fsae_MotorState_init_default             {_fsae_MotorPosition_MIN, 0, 0, 0, 0, 0, 0}
#define fsae_VehicleState_init_default           {0, _fsae_DrivingMode_MIN, 0, 0, 0, _fsae_VcuStatus_MIN, 0, {fsae_MotorState_init_default, fsae_MotorState_init_default, fsae_MotorState_init_default, fsae_MotorState_init_default}}
#define fsae_TelemetryFrame_init_default         {false, fsae_PacketHeader_init_default, false, fsae_FastTelemetry_init_default, false, fsae_VehicleState_init_default, false, fsae_BmsSummary_init_default, false, fsae_BmsDetail_init_default, false, fsae_ThermalSummary_init_default, {{NULL}, NULL}}
#define fsae_PacketHeader_init_zero              {0, 0, 0}
#define fsae_Alarm_init_zero                     {0, _fsae_AlarmSeverity_MIN, ""}
#define fsae_FastTelemetry_init_zero             {0, 0, 0, _fsae_DrivingMode_MIN, 0}
#define fsae_BmsSummary_init_zero                {0, 0, 0, 0, 0, 0, 0, _fsae_ImdState_MIN, _fsae_WorkState_MIN}
#define fsae_BatteryModule_init_zero             {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define fsae_BmsDetail_init_zero                 {0, {fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero}}
#define fsae_ThermalRawChunk_init_zero           {_fsae_MotorPosition_MIN, 0, 0, 0, 0}
#define fsae_ThermalSensorSummary_init_zero      {_fsae_MotorPosition_MIN, 0, 0, 0, 0, {fsae_ThermalRawChunk_init_zero, fsae_ThermalRawChunk_init_zero, fsae_ThermalRawChunk_init_zero, fsae_ThermalRawChunk_init_zero}}
#define fsae_ThermalSummary_init_zero            {0, {fsae_ThermalSensorSummary_init_zero, fsae_ThermalSensorSummary_init_zero, fsae_ThermalSensorSummary_init_zero, fsae_ThermalSensorSummary_init_zero}}
#define fsae_MotorState_init_zero                {_fsae_MotorPosition_MIN, 0, 0, 0, 0, 0, 0}
#define fsae_VehicleState_init_zero              {0, _fsae_DrivingMode_MIN, 0, 0, 0, _fsae_VcuStatus_MIN, 0, {fsae_MotorState_init_zero, fsae_MotorState_init_zero, fsae_MotorState_init_zero, fsae_MotorState_init_zero}}
#define fsae_TelemetryFrame_init_zero            {false, fsae_PacketHeader_init_zero, false, fsae_FastTelemetry_init_zero, false, fsae_VehicleState_init_zero, false, fsae_BmsSummary_init_zero, false, fsae_BmsDetail_init_zero, false, fsae_ThermalSummary_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define fsae_PacketHeader_timestamp_ms_tag       1
#define fsae_PacketHeader_seq_tag                2
#define fsae_PacketHeader_source_id_tag          3
#define fsae_Alarm_alarm_id_tag                  1
#define fsae_Alarm_severity_tag                  2
#define fsae_Alarm_message_tag                   3
#define fsae_FastTelemetry_hv_voltage_dv_tag     1
#define fsae_FastTelemetry_hv_current_ma_tag     2
#define fsae_FastTelemetry_battery_temp_max_c_tag 3
#define fsae_FastTelemetry_driving_mode_tag      4
#define fsae_FastTelemetry_speed_kmh_tag         5
#define fsae_BmsSummary_total_voltage_tag        1
#define fsae_BmsSummary_total_current_tag        2
#define fsae_BmsSummary_soc_pct_tag              3
#define fsae_BmsSummary_max_temp_c_tag           4
#define fsae_BmsSummary_min_temp_c_tag           5
#define fsae_BmsSummary_max_cell_mv_tag          6
#define fsae_BmsSummary_min_cell_mv_tag          7
#define fsae_BmsSummary_imd_state_tag            8
#define fsae_BmsSummary_work_state_tag           9
#define fsae_BatteryModule_module_id_tag         1
#define fsae_BatteryModule_cell_mv_tag           2
#define fsae_BatteryModule_temp_dc_tag           3
#define fsae_BmsDetail_modules_tag               1
#define fsae_ThermalRawChunk_position_tag        1
#define fsae_ThermalRawChunk_frame_id_tag        2
#define fsae_ThermalRawChunk_chunk_index_tag     3
#define fsae_ThermalRawChunk_chunk_count_tag     4
#define fsae_ThermalRawChunk_pixel_temp_dc_tag   5
#define fsae_ThermalSensorSummary_position_tag   1
#define fsae_ThermalSensorSummary_min_temp_dc_tag 2
#define fsae_ThermalSensorSummary_max_temp_dc_tag 3
#define fsae_ThermalSensorSummary_avg_temp_dc_tag 4
#define fsae_ThermalSensorSummary_chunks_tag     5
#define fsae_ThermalSummary_sensors_tag          1
#define fsae_MotorState_position_tag             1
#define fsae_MotorState_rpm_tag                  2
#define fsae_MotorState_torque_nm_tag            3
#define fsae_MotorState_power_w_tag              4
#define fsae_MotorState_motor_temp_dc_tag        5
#define fsae_MotorState_inverter_temp_dc_tag     6
#define fsae_MotorState_motor_error_tag          7
#define fsae_VehicleState_speed_kmh_tag          1
#define fsae_VehicleState_driving_mode_tag       2
#define fsae_VehicleState_throttle_position_tag  3
#define fsae_VehicleState_brake_position_tag     4
#define fsae_VehicleState_ready_to_drive_tag     5
#define fsae_VehicleState_vcu_status_tag         6
#define fsae_VehicleState_motors_tag             7
#define fsae_TelemetryFrame_packet_header_tag    1
#define fsae_TelemetryFrame_fast_telemetry_tag   2
#define fsae_TelemetryFrame_vehicle_state_tag    3
#define fsae_TelemetryFrame_bms_summary_tag      4
#define fsae_TelemetryFrame_bms_detail_tag       5
#define fsae_TelemetryFrame_thermal_summary_tag  6
#define fsae_TelemetryFrame_alarm_tag            7

/* Struct field encoding specification for nanopb */
#define fsae_PacketHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               2) \
X(a, STATIC,   SINGULAR, UINT32,   source_id,         3)
#define fsae_PacketHeader_CALLBACK NULL
#define fsae_PacketHeader_DEFAULT NULL

#define fsae_Alarm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   alarm_id,          1) \
X(a, STATIC,   SINGULAR, UENUM,    severity,          2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define fsae_Alarm_CALLBACK NULL
#define fsae_Alarm_DEFAULT NULL

#define fsae_FastTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   hv_voltage_dv,     1) \
X(a, STATIC,   SINGULAR, SINT32,   hv_current_ma,     2) \
X(a, STATIC,   SINGULAR, SINT32,   battery_temp_max_c,   3) \
X(a, STATIC,   SINGULAR, UENUM,    driving_mode,      4) \
X(a, STATIC,   SINGULAR, UINT32,   speed_kmh,         5)
#define fsae_FastTelemetry_CALLBACK NULL
#define fsae_FastTelemetry_DEFAULT NULL

#define fsae_BmsSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_voltage,     1) \
X(a, STATIC,   SINGULAR, SINT32,   total_current,     2) \
X(a, STATIC,   SINGULAR, UINT32,   soc_pct,           3) \
X(a, STATIC,   SINGULAR, SINT32,   max_temp_c,        4) \
X(a, STATIC,   SINGULAR, SINT32,   min_temp_c,        5) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_mv,       6) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_mv,       7) \
X(a, STATIC,   SINGULAR, UENUM,    imd_state,         8) \
X(a, STATIC,   SINGULAR, UENUM,    work_state,        9)
#define fsae_BmsSummary_CALLBACK NULL
#define fsae_BmsSummary_DEFAULT NULL

#define fsae_BatteryModule_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   module_id,         1) \
X(a, STATIC,   REPEATED, UINT32,   cell_mv,           2) \
X(a, STATIC,   REPEATED, SINT32,   temp_dc,           3)
#define fsae_BatteryModule_CALLBACK NULL
#define fsae_BatteryModule_DEFAULT NULL

#define fsae_BmsDetail_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  modules,           1)
#define fsae_BmsDetail_CALLBACK NULL
#define fsae_BmsDetail_DEFAULT NULL
#define fsae_BmsDetail_modules_MSGTYPE fsae_BatteryModule

#define fsae_ThermalRawChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    position,          1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_id,          2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       3) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_count,       4) \
X(a, STATIC,   SINGULAR, SINT32,   pixel_temp_dc,     5)
#define fsae_ThermalRawChunk_CALLBACK NULL
#define fsae_ThermalRawChunk_DEFAULT NULL

#define fsae_ThermalSensorSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    position,          1) \
X(a, STATIC,   SINGULAR, SINT32,   min_temp_dc,       2) \
X(a, STATIC,   SINGULAR, SINT32,   max_temp_dc,       3) \
X(a, STATIC,   SINGULAR, SINT32,   avg_temp_dc,       4) \
X(a, STATIC,   REPEATED, MESSAGE,  chunks,            5)
#define fsae_ThermalSensorSummary_CALLBACK NULL
#define fsae_ThermalSensorSummary_DEFAULT NULL
#define fsae_ThermalSensorSummary_chunks_MSGTYPE fsae_ThermalRawChunk

#define fsae_ThermalSummary_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  sensors,           1)
#define fsae_ThermalSummary_CALLBACK NULL
#define fsae_ThermalSummary_DEFAULT NULL
#define fsae_ThermalSummary_sensors_MSGTYPE fsae_ThermalSensorSummary

#define fsae_MotorState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    position,          1) \
X(a, STATIC,   SINGULAR, SINT32,   rpm,               2) \
X(a, STATIC,   SINGULAR, SINT32,   torque_nm,         3) \
X(a, STATIC,   SINGULAR, SINT32,   power_w,           4) \
X(a, STATIC,   SINGULAR, SINT32,   motor_temp_dc,     5) \
X(a, STATIC,   SINGULAR, SINT32,   inverter_temp_dc,   6) \
X(a, STATIC,   SINGULAR, SINT32,   motor_error,       7)
#define fsae_MotorState_CALLBACK NULL
#define fsae_MotorState_DEFAULT NULL

#define fsae_VehicleState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   speed_kmh,         1) \
X(a, STATIC,   SINGULAR, UENUM,    driving_mode,      2) \
X(a, STATIC,   SINGULAR, UINT32,   throttle_position,   3) \
X(a, STATIC,   SINGULAR, UINT32,   brake_position,    4) \
X(a, STATIC,   SINGULAR, BOOL,     ready_to_drive,    5) \
X(a, STATIC,   SINGULAR, UENUM,    vcu_status,        6) \
X(a, STATIC,   REPEATED, MESSAGE,  motors,            7)
#define fsae_VehicleState_CALLBACK NULL
#define fsae_VehicleState_DEFAULT NULL
#define fsae_VehicleState_motors_MSGTYPE fsae_MotorState

#define fsae_TelemetryFrame_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  packet_header,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fast_telemetry,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vehicle_state,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bms_summary,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bms_detail,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  thermal_summary,   6) \
X(a, CALLBACK, REPEATED, MESSAGE,  alarm,             7)
#define fsae_TelemetryFrame_CALLBACK pb_default_field_callback
#define fsae_TelemetryFrame_DEFAULT NULL
#define fsae_TelemetryFrame_packet_header_MSGTYPE fsae_PacketHeader
#define fsae_TelemetryFrame_fast_telemetry_MSGTYPE fsae_FastTelemetry
#define fsae_TelemetryFrame_vehicle_state_MSGTYPE fsae_VehicleState
#define fsae_TelemetryFrame_bms_summary_MSGTYPE fsae_BmsSummary
#define fsae_TelemetryFrame_bms_detail_MSGTYPE fsae_BmsDetail
#define fsae_TelemetryFrame_thermal_summary_MSGTYPE fsae_ThermalSummary
#define fsae_TelemetryFrame_alarm_MSGTYPE fsae_Alarm

extern const pb_msgdesc_t fsae_PacketHeader_msg;
extern const pb_msgdesc_t fsae_Alarm_msg;
extern const pb_msgdesc_t fsae_FastTelemetry_msg;
extern const pb_msgdesc_t fsae_BmsSummary_msg;
extern const pb_msgdesc_t fsae_BatteryModule_msg;
extern const pb_msgdesc_t fsae_BmsDetail_msg;
extern const pb_msgdesc_t fsae_ThermalRawChunk_msg;
extern const pb_msgdesc_t fsae_ThermalSensorSummary_msg;
extern const pb_msgdesc_t fsae_ThermalSummary_msg;
extern const pb_msgdesc_t fsae_MotorState_msg;
extern const pb_msgdesc_t fsae_VehicleState_msg;
extern const pb_msgdesc_t fsae_TelemetryFrame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fsae_PacketHeader_fields &fsae_PacketHeader_msg
#define fsae_Alarm_fields &fsae_Alarm_msg
#define fsae_FastTelemetry_fields &fsae_FastTelemetry_msg
#define fsae_BmsSummary_fields &fsae_BmsSummary_msg
#define fsae_BatteryModule_fields &fsae_BatteryModule_msg
#define fsae_BmsDetail_fields &fsae_BmsDetail_msg
#define fsae_ThermalRawChunk_fields &fsae_ThermalRawChunk_msg
#define fsae_ThermalSensorSummary_fields &fsae_ThermalSensorSummary_msg
#define fsae_ThermalSummary_fields &fsae_ThermalSummary_msg
#define fsae_MotorState_fields &fsae_MotorState_msg
#define fsae_VehicleState_fields &fsae_VehicleState_msg
#define fsae_TelemetryFrame_fields &fsae_TelemetryFrame_msg

/* Maximum encoded size of messages (where known) */
/* fsae_TelemetryFrame_size depends on runtime parameters */
#define FSAE_FSAE_TELEMETRY_PB_H_MAX_SIZE        fsae_BmsDetail_size
#define fsae_Alarm_size                          73
#define fsae_BatteryModule_size                  192
#define fsae_BmsDetail_size                      1170
#define fsae_BmsSummary_size                     46
#define fsae_FastTelemetry_size                  26
#define fsae_MotorState_size                     38
#define fsae_PacketHeader_size                   18
#define fsae_ThermalRawChunk_size                26
#define fsae_ThermalSensorSummary_size           132
#define fsae_ThermalSummary_size                 540
#define fsae_VehicleState_size                   184

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
