/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FSAE_FSAE_TELEMETRY_PB_H_INCLUDED
#define PB_FSAE_FSAE_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _fsae_AlarmSeverity { /* 告警等级 */
    fsae_AlarmSeverity_ALARM_SEVERITY_UNSPECIFIED = 0, /* 未知等级 */
    fsae_AlarmSeverity_ALARM_SEVERITY_INFO = 1, /* 提示 */
    fsae_AlarmSeverity_ALARM_SEVERITY_WARNING = 2, /* 警告 */
    fsae_AlarmSeverity_ALARM_SEVERITY_ERROR = 3, /* 错误 */
    fsae_AlarmSeverity_ALARM_SEVERITY_FATAL = 4 /* 严重故障 */
} fsae_AlarmSeverity;

typedef enum _fsae_DrivingMode { /* 驾驶模式 */
    fsae_DrivingMode_DRIVING_MODE_UNSPECIFIED = 0, /* 未知模式 */
    fsae_DrivingMode_DRIVING_MODE_STANDBY = 1, /* 待机 */
    fsae_DrivingMode_DRIVING_MODE_READY = 2, /* 就绪 */
    fsae_DrivingMode_DRIVING_MODE_DRIVE = 3, /* 行驶 */
    fsae_DrivingMode_DRIVING_MODE_FAULT = 4 /* 故障 */
} fsae_DrivingMode;

typedef enum _fsae_ImdState { /* IMD 状态 */
    fsae_ImdState_IMD_STATE_UNSPECIFIED = 0, /* 未知状态 */
    fsae_ImdState_IMD_STATE_NORMAL = 1, /* 绝缘正常 */
    fsae_ImdState_IMD_STATE_WARNING = 2, /* 绝缘预警 */
    fsae_ImdState_IMD_STATE_FAULT = 3 /* 绝缘故障 */
} fsae_ImdState;

typedef enum _fsae_WorkState { /* 工作状态 */
    fsae_WorkState_WORK_STATE_UNSPECIFIED = 0, /* 未知状态 */
    fsae_WorkState_WORK_STATE_OFF = 1, /* 关闭 */
    fsae_WorkState_WORK_STATE_PRECHARGE = 2, /* 预充 */
    fsae_WorkState_WORK_STATE_ON = 3, /* 工作中 */
    fsae_WorkState_WORK_STATE_FAULT = 4 /* 故障 */
} fsae_WorkState;

typedef enum _fsae_VcuStatus { /* VCU 状态 */
    fsae_VcuStatus_VCU_STATUS_UNSPECIFIED = 0, /* 未知状态 */
    fsae_VcuStatus_VCU_STATUS_OFF = 1, /* 关闭 */
    fsae_VcuStatus_VCU_STATUS_PRECHARGE = 2, /* 预充中 */
    fsae_VcuStatus_VCU_STATUS_HV_ENABLED = 3, /* 高压已建立 */
    fsae_VcuStatus_VCU_STATUS_FAULT = 4 /* 故障 */
} fsae_VcuStatus;

typedef enum _fsae_MotorPosition { /* 电机/轮位位置 */
    fsae_MotorPosition_MOTOR_POSITION_UNSPECIFIED = 0, /* 未知位置 */
    fsae_MotorPosition_MOTOR_POSITION_FRONT_LEFT = 1, /* 左前 */
    fsae_MotorPosition_MOTOR_POSITION_FRONT_RIGHT = 2, /* 右前 */
    fsae_MotorPosition_MOTOR_POSITION_REAR_LEFT = 3, /* 左后 */
    fsae_MotorPosition_MOTOR_POSITION_REAR_RIGHT = 4 /* 右后 */
} fsae_MotorPosition;

/* Struct definitions */
typedef struct _fsae_PacketHeader { /* 通用报文头 */
    uint32_t timestamp_ms; /* 时间戳，单位 ms */
    uint32_t seq; /* 报文序列号 */
    uint32_t source_id; /* 数据源设备 ID */
} fsae_PacketHeader;

typedef struct _fsae_Alarm { /* 告警信息 */
    uint32_t alarm_id; /* 告警 ID */
    fsae_AlarmSeverity severity; /* 告警等级 */
    char message[64]; /* 告警内容 */
} fsae_Alarm;

typedef struct _fsae_FastTelemetry { /* 遥测快报摘要 */
    int32_t hv_voltage_dv; /* 高压电压，单位 0.1V */
    int32_t hv_current_ma; /* 总电流，单位 mA */
    int32_t battery_temp_max_c; /* 电池最高温度，单位摄氏度 */
    fsae_DrivingMode driving_mode; /* 当前驾驶模式 */
    uint32_t speed_kmh; /* 车速，单位 km/h */
} fsae_FastTelemetry;

typedef struct _fsae_BmsSummary { /* BMS 汇总信息 */
    uint32_t total_voltage; /* 电池包总电压，单位 0.1V */
    int32_t total_current; /* 电池包总电流，单位 mA */
    uint32_t soc_pct; /* 荷电状态百分比 */
    int32_t max_temp_c; /* 最高温度，单位摄氏度 */
    int32_t min_temp_c; /* 最低温度，单位摄氏度 */
    uint32_t max_cell_mv; /* 最高单体电压，单位 mV */
    uint32_t min_cell_mv; /* 最低单体电压，单位 mV */
    fsae_ImdState imd_state; /* 绝缘监测状态 */
    fsae_WorkState work_state; /* BMS 工作状态 */
} fsae_BmsSummary;

typedef struct _fsae_BatteryModule { /* 单个电池模组详情 */
    uint32_t module_id; /* 模组编号，建议固定为 1~6 */
    pb_size_t cell_mv_count;
    uint32_t cell_mv[23]; /* 模组内 23 个单体电压，单位 mV，按物理顺序发送 */
    pb_size_t temp_dc_count;
    int32_t temp_dc[8]; /* 模组内 8 个温度点，单位 0.1 摄氏度，按物理顺序发送 */
} fsae_BatteryModule;

typedef struct _fsae_BmsDetail { /* BMS 详细信息 */
    pb_size_t modules_count;
    fsae_BatteryModule modules[6]; /* 6 个电池模组数据，建议固定发送 6 条 */
} fsae_BmsDetail;

typedef struct _fsae_ThermalRawChunk { /* 热成像原始数据分片 */
    fsae_MotorPosition position; /* 对应电机/轮位 */
    uint32_t frame_id; /* 帧编号 */
    uint32_t chunk_index; /* 当前分片索引 */
    uint32_t chunk_count; /* 总分片数量 */
    int32_t pixel_temp_dc; /* 当前分片像素温度，单位 0.01 摄氏度 */
} fsae_ThermalRawChunk;

typedef struct _fsae_ThermalSensorSummary { /* 单个轮位的红外温度摘要 */
    fsae_MotorPosition position; /* 对应电机/轮位 */
    int32_t min_temp_dc; /* 最低温度，单位 0.01 摄氏度 */
    int32_t max_temp_dc; /* 最高温度，单位 0.01 摄氏度 */
    int32_t avg_temp_dc; /* 平均温度，单位 0.01 摄氏度 */
    pb_size_t chunks_count;
    fsae_ThermalRawChunk chunks[4]; /* 原始温度分片列表 */
} fsae_ThermalSensorSummary;

typedef struct _fsae_ThermalSummary { /* 热成像摘要 */
    pb_size_t sensors_count;
    fsae_ThermalSensorSummary sensors[4]; /* 四个轮位的红外温度摘要 */
} fsae_ThermalSummary;

typedef struct _fsae_MotorState { /* 单个电机状态 */
    fsae_MotorPosition position; /* 电机位置 */
    int32_t rpm; /* 电机转速 */
    int32_t torque_nm; /* 电机扭矩，单位 Nm */
    int32_t power_w; /* 电机功率，单位 W */
    int32_t motor_temp_dc; /* 电机温度，单位 0.1 摄氏度 */
    int32_t inverter_temp_dc; /* 电机控制器温度，单位 0.1 摄氏度 */
    int32_t motor_error; /* 电机错误码 */
} fsae_MotorState;

typedef struct _fsae_VehicleState { /* 整车状态 */
    uint32_t speed_kmh; /* 车速，单位 km/h */
    fsae_DrivingMode driving_mode; /* 当前驾驶模式 */
    uint32_t throttle_position; /* 油门开度 */
    uint32_t brake_position; /* 刹车开度 */
    bool ready_to_drive; /* 车辆是否处于 Ready To Drive */
    fsae_VcuStatus vcu_status; /* VCU 状态 */
    pb_size_t motors_count;
    fsae_MotorState motors[4]; /* 四个电机状态列表，按 position 区分 */
} fsae_VehicleState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _fsae_AlarmSeverity_MIN fsae_AlarmSeverity_ALARM_SEVERITY_UNSPECIFIED
#define _fsae_AlarmSeverity_MAX fsae_AlarmSeverity_ALARM_SEVERITY_FATAL
#define _fsae_AlarmSeverity_ARRAYSIZE ((fsae_AlarmSeverity)(fsae_AlarmSeverity_ALARM_SEVERITY_FATAL+1))

#define _fsae_DrivingMode_MIN fsae_DrivingMode_DRIVING_MODE_UNSPECIFIED
#define _fsae_DrivingMode_MAX fsae_DrivingMode_DRIVING_MODE_FAULT
#define _fsae_DrivingMode_ARRAYSIZE ((fsae_DrivingMode)(fsae_DrivingMode_DRIVING_MODE_FAULT+1))

#define _fsae_ImdState_MIN fsae_ImdState_IMD_STATE_UNSPECIFIED
#define _fsae_ImdState_MAX fsae_ImdState_IMD_STATE_FAULT
#define _fsae_ImdState_ARRAYSIZE ((fsae_ImdState)(fsae_ImdState_IMD_STATE_FAULT+1))

#define _fsae_WorkState_MIN fsae_WorkState_WORK_STATE_UNSPECIFIED
#define _fsae_WorkState_MAX fsae_WorkState_WORK_STATE_FAULT
#define _fsae_WorkState_ARRAYSIZE ((fsae_WorkState)(fsae_WorkState_WORK_STATE_FAULT+1))

#define _fsae_VcuStatus_MIN fsae_VcuStatus_VCU_STATUS_UNSPECIFIED
#define _fsae_VcuStatus_MAX fsae_VcuStatus_VCU_STATUS_FAULT
#define _fsae_VcuStatus_ARRAYSIZE ((fsae_VcuStatus)(fsae_VcuStatus_VCU_STATUS_FAULT+1))

#define _fsae_MotorPosition_MIN fsae_MotorPosition_MOTOR_POSITION_UNSPECIFIED
#define _fsae_MotorPosition_MAX fsae_MotorPosition_MOTOR_POSITION_REAR_RIGHT
#define _fsae_MotorPosition_ARRAYSIZE ((fsae_MotorPosition)(fsae_MotorPosition_MOTOR_POSITION_REAR_RIGHT+1))


#define fsae_Alarm_severity_ENUMTYPE fsae_AlarmSeverity

#define fsae_FastTelemetry_driving_mode_ENUMTYPE fsae_DrivingMode

#define fsae_BmsSummary_imd_state_ENUMTYPE fsae_ImdState
#define fsae_BmsSummary_work_state_ENUMTYPE fsae_WorkState



#define fsae_ThermalSensorSummary_position_ENUMTYPE fsae_MotorPosition


#define fsae_ThermalRawChunk_position_ENUMTYPE fsae_MotorPosition

#define fsae_MotorState_position_ENUMTYPE fsae_MotorPosition

#define fsae_VehicleState_driving_mode_ENUMTYPE fsae_DrivingMode
#define fsae_VehicleState_vcu_status_ENUMTYPE fsae_VcuStatus


/* Initializer values for message structs */
#define fsae_PacketHeader_init_default           {0, 0, 0}
#define fsae_Alarm_init_default                  {0, _fsae_AlarmSeverity_MIN, ""}
#define fsae_FastTelemetry_init_default          {0, 0, 0, _fsae_DrivingMode_MIN, 0}
#define fsae_BmsSummary_init_default             {0, 0, 0, 0, 0, 0, 0, _fsae_ImdState_MIN, _fsae_WorkState_MIN}
#define fsae_BatteryModule_init_default          {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define fsae_BmsDetail_init_default              {0, {fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default}}
#define fsae_ThermalSensorSummary_init_default   {_fsae_MotorPosition_MIN, 0, 0, 0, 0, {fsae_ThermalRawChunk_init_default, fsae_ThermalRawChunk_init_default, fsae_ThermalRawChunk_init_default, fsae_ThermalRawChunk_init_default}}
#define fsae_ThermalSummary_init_default         {0, {fsae_ThermalSensorSummary_init_default, fsae_ThermalSensorSummary_init_default, fsae_ThermalSensorSummary_init_default, fsae_ThermalSensorSummary_init_default}}
#define fsae_ThermalRawChunk_init_default        {_fsae_MotorPosition_MIN, 0, 0, 0, 0}
#define fsae_MotorState_init_default             {_fsae_MotorPosition_MIN, 0, 0, 0, 0, 0, 0}
#define fsae_VehicleState_init_default           {0, _fsae_DrivingMode_MIN, 0, 0, 0, _fsae_VcuStatus_MIN, 0, {fsae_MotorState_init_default, fsae_MotorState_init_default, fsae_MotorState_init_default, fsae_MotorState_init_default}}
#define fsae_PacketHeader_init_zero              {0, 0, 0}
#define fsae_Alarm_init_zero                     {0, _fsae_AlarmSeverity_MIN, ""}
#define fsae_FastTelemetry_init_zero             {0, 0, 0, _fsae_DrivingMode_MIN, 0}
#define fsae_BmsSummary_init_zero                {0, 0, 0, 0, 0, 0, 0, _fsae_ImdState_MIN, _fsae_WorkState_MIN}
#define fsae_BatteryModule_init_zero             {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define fsae_BmsDetail_init_zero                 {0, {fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero}}
#define fsae_ThermalSensorSummary_init_zero      {_fsae_MotorPosition_MIN, 0, 0, 0, 0, {fsae_ThermalRawChunk_init_zero, fsae_ThermalRawChunk_init_zero, fsae_ThermalRawChunk_init_zero, fsae_ThermalRawChunk_init_zero}}
#define fsae_ThermalSummary_init_zero            {0, {fsae_ThermalSensorSummary_init_zero, fsae_ThermalSensorSummary_init_zero, fsae_ThermalSensorSummary_init_zero, fsae_ThermalSensorSummary_init_zero}}
#define fsae_ThermalRawChunk_init_zero           {_fsae_MotorPosition_MIN, 0, 0, 0, 0}
#define fsae_MotorState_init_zero                {_fsae_MotorPosition_MIN, 0, 0, 0, 0, 0, 0}
#define fsae_VehicleState_init_zero              {0, _fsae_DrivingMode_MIN, 0, 0, 0, _fsae_VcuStatus_MIN, 0, {fsae_MotorState_init_zero, fsae_MotorState_init_zero, fsae_MotorState_init_zero, fsae_MotorState_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define fsae_PacketHeader_timestamp_ms_tag       1
#define fsae_PacketHeader_seq_tag                2
#define fsae_PacketHeader_source_id_tag          3
#define fsae_Alarm_alarm_id_tag                  1
#define fsae_Alarm_severity_tag                  2
#define fsae_Alarm_message_tag                   3
#define fsae_FastTelemetry_hv_voltage_dv_tag     1
#define fsae_FastTelemetry_hv_current_ma_tag     2
#define fsae_FastTelemetry_battery_temp_max_c_tag 3
#define fsae_FastTelemetry_driving_mode_tag      4
#define fsae_FastTelemetry_speed_kmh_tag         5
#define fsae_BmsSummary_total_voltage_tag        1
#define fsae_BmsSummary_total_current_tag        2
#define fsae_BmsSummary_soc_pct_tag              3
#define fsae_BmsSummary_max_temp_c_tag           4
#define fsae_BmsSummary_min_temp_c_tag           5
#define fsae_BmsSummary_max_cell_mv_tag          6
#define fsae_BmsSummary_min_cell_mv_tag          7
#define fsae_BmsSummary_imd_state_tag            8
#define fsae_BmsSummary_work_state_tag           9
#define fsae_BatteryModule_module_id_tag         1
#define fsae_BatteryModule_cell_mv_tag           2
#define fsae_BatteryModule_temp_dc_tag           3
#define fsae_BmsDetail_modules_tag               1
#define fsae_ThermalRawChunk_position_tag        1
#define fsae_ThermalRawChunk_frame_id_tag        2
#define fsae_ThermalRawChunk_chunk_index_tag     3
#define fsae_ThermalRawChunk_chunk_count_tag     4
#define fsae_ThermalRawChunk_pixel_temp_dc_tag   5
#define fsae_ThermalSensorSummary_position_tag   1
#define fsae_ThermalSensorSummary_min_temp_dc_tag 2
#define fsae_ThermalSensorSummary_max_temp_dc_tag 3
#define fsae_ThermalSensorSummary_avg_temp_dc_tag 4
#define fsae_ThermalSensorSummary_chunks_tag     5
#define fsae_ThermalSummary_sensors_tag          1
#define fsae_MotorState_position_tag             1
#define fsae_MotorState_rpm_tag                  2
#define fsae_MotorState_torque_nm_tag            3
#define fsae_MotorState_power_w_tag              4
#define fsae_MotorState_motor_temp_dc_tag        5
#define fsae_MotorState_inverter_temp_dc_tag     6
#define fsae_MotorState_motor_error_tag          7
#define fsae_VehicleState_speed_kmh_tag          1
#define fsae_VehicleState_driving_mode_tag       2
#define fsae_VehicleState_throttle_position_tag  3
#define fsae_VehicleState_brake_position_tag     4
#define fsae_VehicleState_ready_to_drive_tag     5
#define fsae_VehicleState_vcu_status_tag         6
#define fsae_VehicleState_motors_tag             7

/* Struct field encoding specification for nanopb */
#define fsae_PacketHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               2) \
X(a, STATIC,   SINGULAR, UINT32,   source_id,         3)
#define fsae_PacketHeader_CALLBACK NULL
#define fsae_PacketHeader_DEFAULT NULL

#define fsae_Alarm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   alarm_id,          1) \
X(a, STATIC,   SINGULAR, UENUM,    severity,          2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define fsae_Alarm_CALLBACK NULL
#define fsae_Alarm_DEFAULT NULL

#define fsae_FastTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   hv_voltage_dv,     1) \
X(a, STATIC,   SINGULAR, SINT32,   hv_current_ma,     2) \
X(a, STATIC,   SINGULAR, SINT32,   battery_temp_max_c,   3) \
X(a, STATIC,   SINGULAR, UENUM,    driving_mode,      4) \
X(a, STATIC,   SINGULAR, UINT32,   speed_kmh,         5)
#define fsae_FastTelemetry_CALLBACK NULL
#define fsae_FastTelemetry_DEFAULT NULL

#define fsae_BmsSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_voltage,     1) \
X(a, STATIC,   SINGULAR, SINT32,   total_current,     2) \
X(a, STATIC,   SINGULAR, UINT32,   soc_pct,           3) \
X(a, STATIC,   SINGULAR, SINT32,   max_temp_c,        4) \
X(a, STATIC,   SINGULAR, SINT32,   min_temp_c,        5) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_mv,       6) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_mv,       7) \
X(a, STATIC,   SINGULAR, UENUM,    imd_state,         8) \
X(a, STATIC,   SINGULAR, UENUM,    work_state,        9)
#define fsae_BmsSummary_CALLBACK NULL
#define fsae_BmsSummary_DEFAULT NULL

#define fsae_BatteryModule_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   module_id,         1) \
X(a, STATIC,   REPEATED, UINT32,   cell_mv,           2) \
X(a, STATIC,   REPEATED, SINT32,   temp_dc,           3)
#define fsae_BatteryModule_CALLBACK NULL
#define fsae_BatteryModule_DEFAULT NULL

#define fsae_BmsDetail_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  modules,           1)
#define fsae_BmsDetail_CALLBACK NULL
#define fsae_BmsDetail_DEFAULT NULL
#define fsae_BmsDetail_modules_MSGTYPE fsae_BatteryModule

#define fsae_ThermalSensorSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    position,          1) \
X(a, STATIC,   SINGULAR, SINT32,   min_temp_dc,       2) \
X(a, STATIC,   SINGULAR, SINT32,   max_temp_dc,       3) \
X(a, STATIC,   SINGULAR, SINT32,   avg_temp_dc,       4) \
X(a, STATIC,   REPEATED, MESSAGE,  chunks,            5)
#define fsae_ThermalSensorSummary_CALLBACK NULL
#define fsae_ThermalSensorSummary_DEFAULT NULL
#define fsae_ThermalSensorSummary_chunks_MSGTYPE fsae_ThermalRawChunk

#define fsae_ThermalSummary_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  sensors,           1)
#define fsae_ThermalSummary_CALLBACK NULL
#define fsae_ThermalSummary_DEFAULT NULL
#define fsae_ThermalSummary_sensors_MSGTYPE fsae_ThermalSensorSummary

#define fsae_ThermalRawChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    position,          1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_id,          2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       3) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_count,       4) \
X(a, STATIC,   SINGULAR, SINT32,   pixel_temp_dc,     5)
#define fsae_ThermalRawChunk_CALLBACK NULL
#define fsae_ThermalRawChunk_DEFAULT NULL

#define fsae_MotorState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    position,          1) \
X(a, STATIC,   SINGULAR, SINT32,   rpm,               2) \
X(a, STATIC,   SINGULAR, SINT32,   torque_nm,         3) \
X(a, STATIC,   SINGULAR, SINT32,   power_w,           4) \
X(a, STATIC,   SINGULAR, SINT32,   motor_temp_dc,     5) \
X(a, STATIC,   SINGULAR, SINT32,   inverter_temp_dc,   6) \
X(a, STATIC,   SINGULAR, SINT32,   motor_error,       7)
#define fsae_MotorState_CALLBACK NULL
#define fsae_MotorState_DEFAULT NULL

#define fsae_VehicleState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   speed_kmh,         1) \
X(a, STATIC,   SINGULAR, UENUM,    driving_mode,      2) \
X(a, STATIC,   SINGULAR, UINT32,   throttle_position,   3) \
X(a, STATIC,   SINGULAR, UINT32,   brake_position,    4) \
X(a, STATIC,   SINGULAR, BOOL,     ready_to_drive,    5) \
X(a, STATIC,   SINGULAR, UENUM,    vcu_status,        6) \
X(a, STATIC,   REPEATED, MESSAGE,  motors,            7)
#define fsae_VehicleState_CALLBACK NULL
#define fsae_VehicleState_DEFAULT NULL
#define fsae_VehicleState_motors_MSGTYPE fsae_MotorState

extern const pb_msgdesc_t fsae_PacketHeader_msg;
extern const pb_msgdesc_t fsae_Alarm_msg;
extern const pb_msgdesc_t fsae_FastTelemetry_msg;
extern const pb_msgdesc_t fsae_BmsSummary_msg;
extern const pb_msgdesc_t fsae_BatteryModule_msg;
extern const pb_msgdesc_t fsae_BmsDetail_msg;
extern const pb_msgdesc_t fsae_ThermalSensorSummary_msg;
extern const pb_msgdesc_t fsae_ThermalSummary_msg;
extern const pb_msgdesc_t fsae_ThermalRawChunk_msg;
extern const pb_msgdesc_t fsae_MotorState_msg;
extern const pb_msgdesc_t fsae_VehicleState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fsae_PacketHeader_fields &fsae_PacketHeader_msg
#define fsae_Alarm_fields &fsae_Alarm_msg
#define fsae_FastTelemetry_fields &fsae_FastTelemetry_msg
#define fsae_BmsSummary_fields &fsae_BmsSummary_msg
#define fsae_BatteryModule_fields &fsae_BatteryModule_msg
#define fsae_BmsDetail_fields &fsae_BmsDetail_msg
#define fsae_ThermalSensorSummary_fields &fsae_ThermalSensorSummary_msg
#define fsae_ThermalSummary_fields &fsae_ThermalSummary_msg
#define fsae_ThermalRawChunk_fields &fsae_ThermalRawChunk_msg
#define fsae_MotorState_fields &fsae_MotorState_msg
#define fsae_VehicleState_fields &fsae_VehicleState_msg

/* Maximum encoded size of messages (where known) */
#define FSAE_FSAE_TELEMETRY_PB_H_MAX_SIZE        fsae_BmsDetail_size
#define fsae_Alarm_size                          73
#define fsae_BatteryModule_size                  192
#define fsae_BmsDetail_size                      1170
#define fsae_BmsSummary_size                     46
#define fsae_FastTelemetry_size                  26
#define fsae_MotorState_size                     38
#define fsae_PacketHeader_size                   18
#define fsae_ThermalRawChunk_size                26
#define fsae_ThermalSensorSummary_size           132
#define fsae_ThermalSummary_size                 540
#define fsae_VehicleState_size                   184

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
